services:
  - type: web
    name: justfall-ws
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: sh server/render_build.sh
    startCommand: sh server/render_start.sh
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
